server:
  port: 8920
  servlet:
    context-path: /aimodel
    session:
      cookie:
        name: AIMODEL-DEV-SESSION
  tomcat:
    threads:
      max: 20
# 日志配置
logging:
  level:
    #不同目录下的日志可配置不同级别
    org.springfromework.web: INFO
    org.hibernate: ERROR
spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/aimodel?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 30
        max-wait: 3000
  thymeleaf:
    cache: false
security:
  oauth2:
    client:
      client-id: aimodel
      client-secret: d11ead29d1994323b95c5c9bc69d7aba
      access-token-uri: http://zklc.xiaotunyun.com/schoolcloud-oauthserver/oauth/token
      user-authorization-uri: https://zklc.xiaotunyun.com/schoolcloud-oauthserver/oauth/authorize
      client-authentication-scheme: header
    resource:
      user-info-uri: http://zklc.xiaotunyun.com/schoolcloud-oauthserver/api/userinfo
  #swgger配置
sys:
   swagger:
      #swgger启用标识  true启用 false不启用
      enable-swgger: true
   netname: http://zklc.xiaotunyun.com