server:
  port: 8920
  servlet:
    context-path: /aimodel
    session:
      cookie:
        name: AIMODEL-DEV-SESSION
  tomcat:
    threads:
      max: 20
# 日志配置
logging:
  level:
    #不同目录下的日志可配置不同级别
    org.springfromework.web: INFO
    org.hibernate: ERROR
spring:
  datasource: 
    url: jdbc:mysql://192.168.100.238:3306/aimodel?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 30
        max-wait: 3000
  thymeleaf:
    cache: false
security:
  oauth2:
    client:
      client-id: aimodel-local
      client-secret: aimodel-local
      access-token-uri: http://192.168.100.238/schoolcloud-oauthserver/oauth/token
      user-authorization-uri: http://192.168.100.238/schoolcloud-oauthserver/oauth/authorize
      client-authentication-scheme: header
    resource:
      user-info-uri: http://192.168.100.238/schoolcloud-oauthserver/api/userinfo
  #swgger配置
sys:
   swagger:
      #swgger启用标识  true启用 false不启用
      enable-swgger: true
   netname: http://192.168.100.238