package com.zklcsoftware.aimodel.repository.impl;

import com.zklcsoftware.basic.repository.BaseRepositoryExtImpl;
import com.zklcsoftware.aimodel.repository.TAiUserSessionModelContextKeysRepositoryExt;

public class TAiUserSessionModelContextKeysRepositoryImpl extends BaseRepositoryExtImpl implements TAiUserSessionModelContextKeysRepositoryExt {
	
}